name = "Brut"
license = "MIT"
licenselink = "https://github.com/robjloranger/brut/blob/master/LICENSE"
description = "A very minimal brutalist theme for hugo"
homepage = "https://robloranger.ca/brut"
tags = ["minimal", "clean", "semantic", "programming"]
features = ["pagination"]
version = "0.1.0"
min_version = "0.41"
lang = "en"

[author]
  name = "rob j loranger"
  homepage = "https://robloranger.ca"
  email = "hello@robloranger.ca"
